GNB_EVENT_OBJS =                       \
       ./gnb_event.o                   \
       ./gnb_network_service.o         \
       ./gnb_address.o                 \
       ./gnb_buf.o                     \
       ./gnb_lru32.o                   \
       ./gnb_doubly_linked_list.o      \
       ./gnb_hash32.o                  \
       ./gnb_payload16.o               \
       ./gnb_time.o                    \
       ./gnb_fixed_list.o              \
       ./gnb_fixed_list_store.o        \
       ./gnb_fixed_pool.o              \
       ./gnb_alloc.o


GNB_UDP_OVER_TCP_OBJS =                \
       ./service/gnb_udp_over_tcp.o    \
       ./service/uot_udp_service.o     \
       ./service/uot_tcp_service.o


